apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: kotsadm
spec:
  template:
    spec:
      containers:
      - name: kotsadm
        env:
        - name: HTTP_PROXY
          value: "${PROXY_ADDRESS}"
        - name: HTTPS_PROXY
          value: "${PROXY_HTTPS_ADDRESS}"
        - name: NO_PROXY
          value: "${NO_PROXY_ADDRESSES}"
