apiVersion: apps/v1
kind: Deployment
metadata:
  name: kotsadm-operator
spec:
  selector:
    matchLabels:
      app: kotsadm-operator
  template:
    metadata:
      labels:
        app: kotsadm-operator
    spec:
      securityContext:
        runAsUser: 1001
      restartPolicy: Always
      containers:
        - name: kotsadm-operator
          image: kotsadm-operator
          imagePullPolicy: Always
          resources:
            limits:
              cpu: 200m
              memory: 1000Mi
            requests:
              cpu: 100m
              memory: 500Mi
          env:
            - name: KOTSADM_API_ENDPOINT
              value: http://kotsadm-api:3000
            - name: KOTSADM_TOKEN
              value: this-is-definitely-not-a-secret
            - name: KOTSADM_TARGET_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
