
---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  annotations:
    controller-gen.kubebuilder.io/version: v0.5.0
  creationTimestamp: null
  name: helmcharts.kots.io
spec:
  group: kots.io
  names:
    kind: HelmChart
    listKind: HelmChartList
    plural: helmcharts
    singular: helmchart
  scope: Namespaced
  versions:
  - name: v1beta1
    schema:
      openAPIV3Schema:
        description: HelmChart is the Schema for the helmchart API
        properties:
          apiVersion:
            description: 'APIVersion defines the versioned schema of this representation
              of an object. Servers should convert recognized schemas to the latest
              internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
            type: string
          kind:
            description: 'Kind is a string value representing the REST resource this
              object represents. Servers may infer this from the endpoint the client
              submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
            type: string
          metadata:
            type: object
          spec:
            description: HelmChartSpec defines the desired state of HelmChartSpec
            properties:
              builder:
                additionalProperties: {}
                type: object
              chart:
                properties:
                  chartVersion:
                    type: string
                  name:
                    type: string
                required:
                - chartVersion
                - name
                type: object
              exclude:
                description: BoolOrString is a type that can hold an bool or a string.  When
                  used in JSON or YAML marshalling and unmarshalling, it produces
                  or consumes the inner type.  This allows you to have, for example,
                  a JSON field that can accept a booolean string or raw bool.
                type: BoolString
              helmVersion:
                type: string
              namespace:
                type: string
              optionalValues:
                items:
                  properties:
                    recursiveMerge:
                      type: boolean
                    values:
                      additionalProperties: {}
                      type: object
                    when:
                      type: string
                  required:
                  - recursiveMerge
                  - when
                  type: object
                type: array
              useHelmInstall:
                type: boolean
              values:
                additionalProperties: {}
                type: object
            required:
            - chart
            type: object
          status:
            description: HelmChartStatus defines the observed state of HelmChart
            type: object
        type: object
    served: true
    storage: true
    subresources:
      status: {}
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: []
  storedVersions: []
