project_name: kots
release:
  github:
    owner: replicatedhq
    name: kots
builds:
  - id: kots
    goos:
    - linux
    - windows
    - darwin
    goarch:
    - amd64
    - "386"
    env:
      - CGO_ENABLED=0
      - GO111MODULE=on
    main: cmd/kots/main.go
    ldflags: -s -w
      -X github.com/replicatedhq/kots/pkg/version.version={{.Version}}
      -X github.com/replicatedhq/kots/pkg/version.gitSHA={{.FullCommit}}
      -X github.com/replicatedhq/kots/pkg/version.buildTime={{.Date}}
      -extldflags "-static"
    flags: -tags netgo -installsuffix netgo
    binary: kots
    hooks: {}
  - id: so
    goos:
    - linux
    goarch:
    - amd64
    env:
      - CGO_ENABLED=1
      - GO111MODULE=on
    main: ./ffi
    ldflags: -s -w
      -X github.com/replicatedhq/kots/pkg/version.version={{.Version}}
      -X github.com/replicatedhq/kots/pkg/version.gitSHA={{.FullCommit}}
      -X github.com/replicatedhq/kots/pkg/version.buildTime={{.Date}}
    flags: -buildmode=c-shared
    binary: kots.so
    hooks: {}

archives:
  - id: kots
    builds:
      - kots
    format: tar.gz
    format_overrides:
      - goos: windows
        format: zip
    name_template: '{{ .Binary }}_{{ .Os }}_{{ .Arch }}'
    files:
      - licence*
      - LICENCE*
      - license*
      - LICENSE*
      - readme*
      - README*
      - changelog*
      - CHANGELOG*
  - id: kots.so
    builds:
      - so
    format: tar.gz
    name_template: '{{ .Binary }}_{{ .Os }}_{{ .Arch }}'
    files:
      - licence*
      - LICENCE*
      - license*
      - LICENSE*
      - readme*
      - README*
      - changelog*
      - CHANGELOG*
