apiVersion: apps/v1
kind: Deployment
metadata:
  name: kotsadm-api
spec:
  template:
    spec:
      containers:
        - name: kotsadm-api
          env:
            - name: DISABLE_SPA_SERVING
              value: "1"
            - name: KOTSADM_TARGET_NAMESPACE
              value: "test"
              valueFrom: ~
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace              
            - name: POSTGRES_URI
              valueFrom:
                secretKeyRef:
                  name: ship-postgres # This secret is created in the migrations directory
                  key: uri
            - name: SHARED_PASSWORD_BCRYPT
              value: $2a$10$xZRsZCYgRDG90N1QEjBxGOBDrDGE.rpcMENV4qNNo7pozYTEPGMwS
            - name: SESSION_KEY
              value: this-is-not-too-secret
            - name: API_ENCRYPTION_KEY
              value: IvWItkB8+ezMisPjSMBknT1PdKjBx7Xc/txZqOP8Y2Oe7+Jy
            - name: S3_BUCKET_NAME
              value: "shipbucket"
            - name: S3_ENDPOINT
              value: http://kotsadm-s3.default.svc.cluster.local:4569/
            - name: S3_ACCESS_KEY_ID
              value: not-a-key
            - name: S3_SECRET_ACCESS_KEY
              value: not-a-secret
            - name: S3_BUCKET_ENDPOINT
              value: "true"
            - name: REPLICATED_API_ENDPOINT
              value: http://replicated-app:3000
            - name: API_ADVERTISE_ENDPOINT
              value: http://127.0.0.1:30065
