name: prebuild codespace
on:
  push:
    branches:
    - main
    - codespaces-sandbox
  workflow_dispatch: 

jobs:
  createPrebuild:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: github/codespaces-precache@v1.1.0
      with:
        regions: WestUs2 EastUs SouthEastAsia
        sku_name: premiumLinux
      env:
        GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
