name: PR license scan

on:
  pull_request_target: # this is safe as these scans do not execute provided code

jobs:
  fossa-scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: "Install FOSSA" 
        uses: replicatedhq/action-fossa/install@main
      - name: "Run FOSSA Scan"
        uses: replicatedhq/action-fossa/scan@main
        with:
          api-key: ${{ secrets.FOSSA_API_KEY }}
