apiVersion: apps/v1
kind: Deployment
metadata:
  name: kotsadm-web
spec:
  template:
    spec:
      containers:
        - name: kotsadm-web
          ports:
            - name: http
              containerPort: 8080